version: '3'
services:

  api:
    image: "haberdashery-api"
    ports:
      - 4040:4040
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}

  ui:
    image: "haberdashery-ui"
    ports:
      - 80:80
    links:
      - api
