from golang:1.18 as build-env

ENV CGO_ENABLED=0
ENV PORT 4040

WORKDIR /app
COPY . .

RUN go mod download
RUN go mod verify
RUN go build -o haberdashery ./cmd/server

FROM alpine

WORKDIR /

COPY --from=build-env /app/haberdashery .

EXPOSE $PORT

CMD ["./haberdashery"]
